import type { Metadata } from 'next';
import { DM_Sans, Instrument_Sans, Instrument_Serif, Playfair_Display, Poppins, Lato, Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import 'nprogress/nprogress.css';
import '@/app/style.css';
import '@/app/responsive.css';
import '@/app/globals.css';
import '@/styles/styles.scss';
import '@/styles/custom.scss';
import '@/styles/badge.scss';
import { PropsWithChildren } from 'react';
import { getMessages } from 'next-intl/server';
import { headers } from 'next/headers';
import { LocaleProvider } from '@/providers/LocaleProvider';
import { TrySubdomainProvider } from '@/providers/TrySubdomainProvider';
import { RouteProgress } from '@/components/RouteProgress';
import ConditionalLayout from '@/components/Layouts/ConditionalLayout';
import RootLayoutScripts from '@/components/RootLayoutScripts';
import ScrollToTop from '@/components/ScrollToTop';
import localFont from 'next/font/local';
import { generateTrySubdomainBlockingScript } from '@/lib/trySubdomainBlockingScript';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  weight: ['400', '600', '700', '800', '500'],
  subsets: ['latin'],
});

const instrumentSans = Instrument_Sans({
  variable: '--font-instrument-sans',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

const instrumentSerif = Instrument_Serif({
  variable: '--font-instrument-serif',
  weight: ['400'],
  subsets: ['latin'],
});

const playfairDisplay = Playfair_Display({
  variable: '--font-playfair-display',
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
});

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

const lato = Lato({
  variable: '--font-lato',
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const lumiType = localFont({
  src: [
    {
      path: '../fonts/LumiTypeREGULAR.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/LumiTypeBOLD.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-lumitype',
  display: 'swap',
});

export async function generateMetadata(): Promise<Metadata> {
  // Temporary debug logging (remove after confirming)
  const envValue = process.env.NEXT_PUBLIC_ALLOW_INDEXING;
  const allowIndexing = envValue === 'true';

  return {
    title: 'LumiMeds',
    description: 'Generated by create next app',
    robots: allowIndexing
      ? 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1'
      : 'noindex, nofollow',
    icons: {
      icon: '/favicon.ico',
    },
  };
}

export default async function RootLayout({ children }: Readonly<PropsWithChildren>) {
  // Get messages for the default locale (en)
  const messages = await getMessages({ locale: 'en' });

  // Get pathname on server side
  const headersList = await headers();

  // Try to get pathname from custom header (set by middleware if needed)
  let pathname = headersList.get('x-pathname');

  // If not available, try to extract from referer header
  if (!pathname) {
    const referer = headersList.get('referer');
    if (referer) {
      try {
        pathname = new URL(referer).pathname;
      } catch {
        pathname = '/';
      }
    } else {
      pathname = '/';
    }
  }

  // Detect try subdomain server-side to prevent hydration mismatch
  const hostHeader = headersList.get('host') || '';
  const { getTrySubdomain } = await import('@/constants');
  const trySubdomain = getTrySubdomain();
  const isTrySubdomain = hostHeader.startsWith(`${trySubdomain}.`);

  // Get environment variables for injection into script
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || '';
  // Import whitelisted routes from constants
  const { TRY_SUBDOMAIN_WHITELISTED_ROUTES } = await import('@/constants');

  // Generate blocking script using utility function
  const blockingScript = generateTrySubdomainBlockingScript({
    subdomain: trySubdomain,
    baseUrl,
    whitelistedRoutes: TRY_SUBDOMAIN_WHITELISTED_ROUTES,
  });

  return (
    <html lang='en'>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: blockingScript,
          }}
        />
      </head>
      <body
        className={`${dmSans.variable} ${instrumentSans.variable} ${instrumentSerif.variable} ${playfairDisplay.variable} ${poppins.variable} ${lato.variable} ${lumiType.variable} ${inter.variable} d-flex flex-column`}
      >
        <ScrollToTop />
        <RouteProgress />
        <LocaleProvider defaultMessages={messages} defaultLocale='en'>
          <TrySubdomainProvider isTrySubdomain={isTrySubdomain}>
            <ConditionalLayout>{children}</ConditionalLayout>
          </TrySubdomainProvider>
        </LocaleProvider>
        <Toaster
          containerClassName='!tw-z-[100000000000000000]'
          toastOptions={{
            duration: 3000,
            position: 'top-right',
            style: {
              maxWidth: 'none',
              whiteSpace: 'nowrap',
            },
          }}
        />
        <RootLayoutScripts />
      </body>
    </html>
  );
}
